Refactor VIEW + Highlight
SacreeBandeDePote/PLD_Agile pull request #21
Opened 2017-11-25 08:13 UTC by P4py

J'ai crée des classes pour rendre le code de View plus lisible ça serait bien qu'on se base là dessus pour la suite du dev du package

2017-11-25 13:39 UTC, PereWoulpy commented
Pourquoi dans le Scheduler tu as changé dans le case glouton, le GloutonTSP en StupidTSP, il faut le garder comme il est.
Il faut changer l'argument dans l'appel du constructer du Scheduler pour changer le type de TSP. D'ailleurs le plus propre serait de faire un Enum (je le ferai)

2017-11-25 13:40 UTC, ghost requested changes
discard the change on the Scheduler class

2017-11-28 07:52 UTC, bdbipbip approved these changes

2017-11-28 07:52 UTC, corentingiraud approved these changes

2017-11-28 07:53 UTC, ghost approved these changes

2017-11-28 07:54 UTC, merged